spring.application.name=journalApp
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=journaldb
spring.mongodb.auto-index-creation=true
#for auto index creation, if you have @Indexed annotation in your document class, it will create index automatically when the application starts