spring.application.name=journalApp
server.port=8081
#spring.mongodb.host=localhost
#spring.mongodb.port=27017
spring.data.mongodb.uri=mongodb://pariatapan0_db_user:Test1234@ac-h52xtev-shard-00-00.iay3eyw.mongodb.net:27017,ac-h52xtev-shard-00-01.iay3eyw.mongodb.net:27017,ac-h52xtev-shard-00-02.iay3eyw.mongodb.net:27017/?ssl=true&replicaSet=atlas-xjqo19-shard-0&authSource=admin&appName=Cluster0
spring.mongodb.database=journaldb
spring.mongodb.auto-index-creation=true
#for auto index creation, if you have @Indexed annotation in your document class, it will create index automatically when the application starts